comment/urls.py
from django.urls import path
from . import views

app_name='comment'
urlpatterns = [
	path('update_comment/', views.update_comment, name="update_comment")
]



	

learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from . import views

urlpatterns = [
	path('admin/',admin.site.urls),
	path('', include('learning_logs.urls', namespace='learning_logs')),
	path('ckeditor',include('ckeditor_uploader.urls')),
	path('comment/',include('comment.urls')),
	path('user/',include('user.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
from django.urls import path
from . import views

app_name='learning_logs'
urlpatterns = [
	path('',views.index, name='index'),
	path('topics/', views.topics, name='topics'),
	path("topics/(?<topic_id>\d+)/",views.topic,name='topic'),
	path('new_topic/',views.new_topic,name='new_topic'),
	path('show_entry/(?<entry_id>\d+)/',views.show_entry,name='show_entry'),
	path('new_entry/(?<topic_id>\d+)/',views.new_entry,name='new_entry'),
	path('edit_entry/(?<entry_id>\d+)/',views.edit_entry,name='edit_entry'),
	# ~ path('del_entry/(?<entry_id>\d+)/',views.del_entry,name='del_entry'),
	path('entry_date/<int:year>/<int:month>',views.entry_date,name='entry_date'),
]

user/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('login/', views.login, name='login'),
	path('register/', views.register, name='register'),
	path('logout/', views.logout, name='logout'),
	path('user_info/', views.user_info, name='user_info'),
	path('change_nickname/', views.change_nickname, name='change_nickname'),
	path('bind_email/', views.bind_email, name='bind_email'),
	path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
	path('change_password/', views.change_password, name='change_password'),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from read_statistics.models import ReadNum
from read_statistics.models import ReadNumExpandMethod

class Topic(models.Model):
	text=models.CharField(max_length=200)
	date_added=models.DateTimeField(auto_now_add=True)
	owner=models.ForeignKey(User,on_delete=models.CASCADE)
	
	def __str__(self):
		return self.text
		
class Entry(models.Model,ReadNumExpandMethod):
	topic=models.ForeignKey(Topic, on_delete=models.CASCADE)
	title=models.CharField(max_length=200,default="")
	text=RichTextUploadingField()
	created_date=models.DateTimeField(auto_now_add=True)
	published_date=models.DateTimeField(auto_now=True)
	
	class Meta:
		verbose_name_plural='entries'
		ordering=['-created_date']
	
	def __str__(self):
		if self.text<str(50):
			return self.text[:50]
		else:
			return self.text[:50]+'...'

learning_logs/forms.py
from django import forms
from .models import Topic,Entry
class TopicForm(forms.ModelForm):
	class Meta:
		model=Topic
		fields={'text'}
		labels={'text':''}
class EntryForm(forms.ModelForm):
	
	class Meta:
		model=Entry
		fields="__all__"

		widgets={'text':forms.Textarea(attrs={'cols':80})}

learning_log/views.py
from django.shortcuts import render,redirect
from django.contrib import auth
from .forms import LoginForm,RegForm
from django.contrib.auth.models import User
from django.urls import reverse

learning_logs/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from .models import Topic,Entry,ReadNum
from comment.models import Comment
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Count
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from .forms import TopicForm,EntryForm
from django.conf import settings
from read_statistics.utils import read_statistics_once_read
from comment.forms import CommentForm

def index(request):
	return render(request, 'index.html')

#def get_entry_list_common_data(request,entries_all_list)

# ~ @login_required
def topics(request):
	entries=Entry.objects.all()
	for entry in entries:
		#user=entry.topic.owner
		topic=entry.topic
	paginator=Paginator(entries,settings.ENTRIES_EACHPAGE_NUM)
	page_num=request.GET.get('page',1)#获取url页码参数（GET请求）
	page_of_entries=paginator.get_page(page_num)
	current_page_num=page_of_entries.number
	#获取当前页码，前后各两页的页码范围
	page_range = list(range(max(current_page_num - 2, 1), current_page_num))+ \
				list(range(current_page_num, min(current_page_num + 2, paginator.num_pages + 1)))
	
	#加上省略页码标记
	if page_range[0] - 1 >=2:
		page_range.insert(0,'...')
	if paginator.num_pages - page_range[-1] >=2:
		page_range.append('...')
	
	#加上首页和尾页
	if page_range[0] !=1:
		page_range.insert(0,1)
	if page_range[-1] != paginator.num_pages:
		page_range.append(paginator.num_pages)
	
	topics=Topic.objects.all()
	topic_list=[]
	for topic in topics:
		topic.entry_count=Entry.objects.filter(topic=topic).count()
		topic_list.append(topic)
	
	entry_dates=Entry.objects.dates('created_date','month',order="DESC")
	entry_dates_dict={}
	for entry_date in entry_dates:
		entry_count=Entry.objects.filter(created_date__year=entry_date.year,
										created_date__month=entry_date.month).count()
		entry_dates_dict[entry_date]=entry_count
		
	context={}
	context['topics']=topic_list
	context['user']=request.user
	context['topic']=topic
	context['entries']=page_of_entries.object_list
	context['page_of_entries']=page_of_entries
	context['page_range']=page_range
	context['entry_dates']=entry_dates_dict
#	context['topics']=Topic.objects.filter(owner=request.user).order_by('date_added')
	return render(request,'learning_logs/topics.html',context)

# ~ @login_required
def topic(request,topic_id):

	topic=get_object_or_404(Topic, id=topic_id)
	entries=Entry.objects.filter(topic_id=topic_id)
	paginator=Paginator(entries,settings.ENTRIES_EACHPAGE_NUM)
	page_num=request.GET.get('page',1)#获取url页码参数（GET请求）
	page_of_entries=paginator.get_page(page_num)
	current_page_num=page_of_entries.number
	#获取当前页码，前后各两页的页码范围
	page_range = list(range(max(current_page_num - 2, 1), current_page_num))+ \
				list(range(current_page_num, min(current_page_num + 2, paginator.num_pages + 1)))
	
	#加上省略页码标记
	if page_range[0] - 1 >=2:
		page_range.insert(0,'...')
	if paginator.num_pages - page_range[-1] >=2:
		page_range.append('...')
	
	#加上首页和尾页
	if page_range[0] !=1:
		page_range.insert(0,1)
	if page_range[-1] != paginator.num_pages:
		page_range.append(paginator.num_pages)
	
	topics=Topic.objects.all()
	topic_list=[]
	for topic in topics:
		topic.entry_count=Entry.objects.filter(topic=topic).count()
		topic_list.append(topic)
	
	entry_dates=Entry.objects.dates('created_date','month',order="DESC")
	entry_dates_dict={}
	for entry_date in entry_dates:
		entry_count=Entry.objects.filter(created_date__year=entry_date.year,
										created_date__month=entry_date.month).count()
		entry_dates_dict[entry_date]=entry_count	
	
	context={}
	context['topic']=topic
	context['entries']=page_of_entries.object_list
	context['page_of_entries']=page_of_entries
	context['page_range']=page_range
	context['entry_dates']=entry_dates_dict
	context['topics']=topic_list
	#context['topics']=Topic.objects.all()

	return render(request, 'learning_logs/topic.html',context)

@login_required
def new_topic(request):
	if request.method != 'POST':
		form=TopicForm()
	else:
		form=TopicForm(request.POST)
		if form.is_valid():
			new_topic=form.save(commit=False)
			new_topic.owner=request.user
			new_topic.save()
			return HttpResponseRedirect(reverse('learning_logs:topics'))
	context={'form':form}
	return render(request,'learning_logs/new_topic.html',context)

# ~ @login_required	
def show_entry(request,entry_id):
	entry=get_object_or_404(Entry,id=entry_id)
	topic=entry.topic
	read_cookie_key=read_statistics_once_read(request,entry)
	
	entry_content_type=ContentType.objects.get_for_model(entry)	
	comments=Comment.objects.filter(content_type=entry_content_type, object_id=entry.id, parent=None)
	
	context={}
	context['previous_entry']=Entry.objects.filter(created_date__gt=entry.created_date).last()
	context['next_entry']=Entry.objects.filter(created_date__lt=entry.created_date).first()
	context['topic']=topic
	context['entry']=entry
	context['comments']=comments.order_by('-comment_time')
	context['comment_form']=CommentForm(initial={'content_type':entry_content_type.model,'object_id':entry_id,'reply_comment_id':0})
	response = render(request,'learning_logs/show_entry.html',context)
	response.set_cookie(read_cookie_key, 'true')
	return response

@login_required			
def new_entry(request,topic_id):
	topic=Topic.objects.get(id=topic_id)
	if request.method!='POST':
		form=EntryForm()
	else:
		form=EntryForm(data=request.POST)
		if form.is_valid():
			new_entry=form.save(commit=False)
			new_entry.topic=topic
			new_entry.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',
												args=[topic_id]))
	context={'form':form, 'topic':topic}
	return render(request,'learning_logs/new_entry.html',context)

@login_required			
def edit_entry(request,entry_id):
	entry=Entry.objects.get(id=entry_id)
	topic=entry.topic
	if request.method!='POST':
		form=EntryForm(instance=entry)
	else:
		form=EntryForm(instance=entry,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('learning_logs:topic',
												args=[topic.id]))
	context={'entry':entry,'topic':topic,'form':form}
	return render(request,'learning_logs/edit_entry.html',context)


# ~ @login_required
# ~ def del_entry(request,entry_id):
	# ~ entry=Entry.objects.get(id=entry_id)
	# ~ topic=entry.topic
	# ~ if topic.owner!=request.user:
		# ~ raise Http404
	# ~ if request.method !='POST':
		# ~ form=EntryForm(instance=entry)
	# ~ else:
		# ~ return entry.remove()
	# ~ context={'topic':topic,'entry':entry,'form':form}
	# ~ return render(request,'learning_logs/del_entry.html',context)
			
def entry_date(request,year,month):
	entries=Entry.objects.filter(created_date__year=year, created_date__month=month)
	for entry in entries:
		user=entry.topic.owner
		topic=entry.topic
	paginator=Paginator(entries,settings.ENTRIES_EACHPAGE_NUM)
	page_num=request.GET.get('page',1)#获取url页码参数（GET请求）
	page_of_entries=paginator.get_page(page_num)
	current_page_num=page_of_entries.number
	#获取当前页码，前后各两页的页码范围
	page_range = list(range(max(current_page_num - 2, 1), current_page_num))+ \
				list(range(current_page_num, min(current_page_num + 2, paginator.num_pages + 1)))
	
	#加上省略页码标记
	if page_range[0] - 1 >=2:
		page_range.insert(0,'...')
	if paginator.num_pages - page_range[-1] >=2:
		page_range.append('...')
	
	#加上首页和尾页
	if page_range[0] !=1:
		page_range.insert(0,1)
	if page_range[-1] != paginator.num_pages:
		page_range.append(paginator.num_pages)
	
	topics=Topic.objects.all()
	topic_list=[]
	for topic in topics:
		topic.entry_count=Entry.objects.filter(topic=topic).count()
		topic_list.append(topic)
		
	context={}
	context['entry_date']= '%s年%s月' % (year,month)
	context['entries']=page_of_entries.object_list
	context['topic']=topic
	context['page_of_entries']=page_of_entries
	context['page_range']=page_range
	context['topics']=topic_list
	context['entry_dates']=Entry.objects.dates('created_date','month',order="DESC")
	return render(request, 'learning_logs/entry_date.html',context)




















	

learning_logs/templates/learning_logs/del_entry.html
{% extends "base.html" %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
<body><p><a href="{% url 'learning_logs:topic' topic_id %}"  style="color:#000">{{topic}}</a></p>
  <p>Delete entry:</p>
  <form action="{% url 'learning_logs:del_entry' entry_id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  </form>
  </body> 
{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "base.html" %}
{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}"  style="color:#000">{{ topic }}</a></h2>
  <h4>Edit entry:</h4>
{% endblock header %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>save changes</button>
    <button name='submit' action="learning_logs/topic.html">返回</button>
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/entry_date.html
{% extends 'base.html' %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
<body> 
<div class="container">
<div class="row">	
	<div class="col-xs-12 col-sm-8 col-md-8 col-lg-9">
		<div class="panel panel-default">
			<div class="panel-heading"> <h2>{{ entry_date }}</h2> 
			</div>
			<div class="panel-body">
				{% for entry in entries %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<a href="{% url 'learning_logs:show_entry' entry.id %}">
						<h3>{{ entry.title }}</h3></a>
						<p>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {{ topic.owner }}&nbsp;&nbsp;
						<span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp; {{ entry.created_date|date:'Y-d-m, H:i' }}
						</p>
						<small>
						<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
						<a href="{% url 'learning_logs:del_entry' entry.id %}">delete entry</a>
						</small>
					</div>
					<div class="panel-body">
						{{ entry.text|striptags|truncatechars_html:50 }}
					</div>
				</div> 
				{% empty %}
					There are no entries for this topic yet.
				{% endfor %}
			</div>
		</div>
		<div class="paginator">
			<ul class="pagination">
			 {# 上一页 #}
				<li >
				{% if page_of_entries.has_previous %}
				 <a href="?page={{ page_of_entries.previous_page_number }}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
				</a>
				{% else %}
					<span aria-hidden="true">&laquo;</span>
				{% endif %}	 
				</li>
				{# 全部页码 #}
				{% for page_num in page_range %}
					{% if page_num == page_of_entries.number %}
						<li class="active"><span>{{page_num}}</span></li>
					{% else %}
						{% if page_num == '...' %}
							<li><span>{{page_num}} </span></li>
						{% else %}
							<li><a href="?page={{ page_num }}">{{page_num}} </a></li>
						{% endif %}
					{% endif %}
				{% endfor %}
				{# 下一页 #}
				<li>
					{% if page_of_entries.has_next %}
						 <a href="?page={{ page_of_entries.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&laquo;</span>
						</a>
					{% else %}
						<span aria-hidden="true">&laquo;</span>
					{% endif %}	 
				</li>
			 </ul>
			<p>
				一共有{{ page_of_entries.paginator.count}}篇博客,
				当前第{{ page_of_entries.number }}页，
				共{{ page_of_entries.paginator.num_pages }}页
			</p>
		</div>
	</div>
	<div class="hidden-xs col-sm-4 col-md-4 col-lg-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Topic</h3>
			</div>
			<div class="panel-body">
				<ul style="list-style-type:none;">
					{% for topic in topics %}
					<li>
					<h3>
						<a href="{% url 'learning_logs:topic' topic.id %}"  style="color:#000">{{ topic }}</a>({{topic.entry_count}})
					</h3>
					</li>
					{% empty %}
					<li>No topics have been added yet.</li>
					{% endfor %}
				</ul>
				<h3><a href="{% url 'learning_logs:new_topic' %}" style="color:#000">
					Add new topic</a>
				</h3>
			</div>
		</div>
	</div>
</div>
</div>
			
			
			
 	<style text="css/text">
	div.panel-heading a{
		color:#000;
	}
	div.paginator{
		text-align:center;
	}
	</style>
 </body> 
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "base.html" %}
{% load static %}
{% block header %}
<script src="http://cdn.hcharts.cn/highcharts/highcharts.js"></script>
	<div class='jumbotron'>
	<h1 style="font-family: 'Lobster' ;">Track your learning.</h1>
	</div>
{% endblock header %}
{% block nav_learninglog_active %}active{% endblock %}
{% block content %}
	<h2>
	  欢迎来到我的网站

	</h2>
	<h2>
    Whenever you learn something new about a topic, make an entry
	summarizing what you've learned.
	</h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Add a new entry:</h2>
{% endblock header %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name='submit' class="btn btn-primary">add entry</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Add a new topic:</h2>
{% endblock header %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
    {% endbuttons %}
  </form>
{% endblock%}

learning_logs/templates/learning_logs/topic.html
{% extends 'base.html' %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
<body> 
<div class="container">
<div class="row">	
	<div class="col-xs-12 col-sm-8 col-md-8 col-lg-9">
		<div class="panel panel-default">

			<div class="panel-heading">

				 <h2>{{ topic }}</h2> 
			<p>
				<a href="{% url 'learning_logs:new_entry' topic.id %}" style="color:#000">add new entry</a>
			</p>
			</div>
			<div class="panel-body">
		{% for entry in entries %}
				<div class="panel panel-default">
					<div class="panel-heading">
						<a href="{% url 'learning_logs:show_entry' entry.id %}">
						<h3>{{ entry.title }}</h3></a>
						<p>
						<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {{topic.owner}}&nbsp;&nbsp;
						<span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp; {{ entry.created_date|date:'Y-d-m, H:i' }}
						阅读:{{ entry.get_read_num}}
						</p>
						<small>
						<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>

						</small>
					</div>
					<div class="panel-body">
						{{ entry.text|striptags|truncatechars_html:120 }}
					</div>
				</div> 
				{% empty %}
					There are no entries for this topic yet.
				{% endfor %}
			</div>
		</div>
		<div class="paginator">
			<ul class="pagination">
			 {# 上一页 #}
				<li >
				{% if page_of_entries.has_previous %}
				 <a href="?page={{ page_of_entries.previous_page_number }}" aria-label="Previous">
					<span aria-hidden="true">&laquo;</span>
				</a>
				{% else %}
					<span aria-hidden="true">&laquo;</span>
				{% endif %}	 
				</li>
				{# 全部页码 #}
				{% for page_num in page_range %}
					{% if page_num == page_of_entries.number %}
						<li class="active"><span>{{page_num}}</span></li>
					{% else %}
						{% if page_num == '...' %}
							<li><span>{{page_num}} </span></li>
						{% else %}
							<li><a href="?page={{ page_num }}">{{page_num}} </a></li>
						{% endif %}
					{% endif %}
				{% endfor %}
				{# 下一页 #}
				<li>
					{% if page_of_entries.has_next %}
						 <a href="?page={{ page_of_entries.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&laquo;</span>
						</a>
					{% else %}
						<span aria-hidden="true">&laquo;</span>
					{% endif %}	 
				</li>
			 </ul>
			<p>
				一共有{{ page_of_entries.paginator.count}}篇博客,
				当前第{{ page_of_entries.number }}页，
				共{{ page_of_entries.paginator.num_pages }}页
			</p>
		</div>
	</div>
	<div class="hidden-xs col-sm-4 col-md-4 col-lg-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Topic</h3>
			</div>
			<div class="panel-body">
				<ul style="list-style-type:none;">
					{% for topic in topics %}
					<li>
					<h3>
						<a href="{% url 'learning_logs:topic' topic.id %}"  style="color:#000">{{ topic.text }}</a>({{topic.entry_count}})
					</h3>
					</li>
					{% empty %}
					<li>No topics have been added yet.</li>
					{% endfor %}
				</ul>
				<h3><a href="{% url 'learning_logs:new_topic' %}" style="color:#000">
					Add new topic</a>
				</h3>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-heading">	日期归档</div>
			<div class="panel-body">
				<ul style="list-style-type:none">
					{% for entry_date,entry_count in entry_dates.items %}
						<li>
							<a href="{% url 'learning_logs:entry_date' entry_date.year entry_date.month %}">
							{{entry_date|date:'Y年m月'}}（{{entry_count}}）</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>
</div>
			
			
			
 	<style text="css/text">
	div.panel-heading a{
		color:#000;
	}
	div.paginator{
		text-align:center;
	}
	div.row a{
		color:#000;
	}
	</style>
 </body> 
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "base.html" %}
{% block nav_topic_active %}active{% endblock %}
{% block content %}
<body>

<div class="container">
<div class="row">	
	<div class="col-xs-12 col-sm-8 col-md-8 col-lg-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Entry</h3>
			</div>
			<div class="panel-body">
			{% for entry in entries %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{% url 'learning_logs:show_entry' entry.id %}">
						<h3>{{ entry.title }}</h3>
					</a>
					<p>
					<span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; {{user}}&nbsp;&nbsp;
					<span class="glyphicon glyphicon-tags" aria-hidden="true"></span> &nbsp;
					<a href="{% url 'learning_logs:topic' topic.id %}"  style="color:#000">
					{{ entry.topic }}</a>&nbsp;&nbsp;
					阅读:{{ entry.get_read_num }}&nbsp;&nbsp;
					<span class="glyphicon glyphicon-time" aria-hidden="true"></span>&nbsp;{{ entry.created_date|date:'Y-m-d' }}
					</p>
				</div>
				<div class="panel-body">
					<p>{{ entry.text|striptags|truncatechars_html:120 }}</p>
				</div>
			</div>
			{% empty %}
			<p>There are no entries for this topic yet.</p>
			{% endfor %}
			</div>
		</div>
			<div class="paginator">
				<ul class="pagination">
				  {# 上一页 #}
					<li >
						{% if page_of_entries.has_previous %}
							 <a href="?page={{ page_of_entries.previous_page_number }}" aria-label="Previous">
								<span aria-hidden="true">&laquo;</span>
							</a>
						{% else %}
							<span aria-hidden="true">&laquo;</span>
						{% endif %}	 
					</li>
					{# 全部页码 #}
					{% for page_num in page_range %}
						{% if page_num == page_of_entries.number %}
							<li class="active"><span>{{page_num}}</span></li>
						{% else %}
							{% if page_num == '...' %}
								<li><span>{{page_num}} </span></li>
							{% else %}
								<li><a href="?page={{ page_num }}">{{page_num}} </a></li>
							{% endif %}
						{% endif %}
					{% endfor %}
					{# 下一页 #}
					<li>
						{% if page_of_entries.has_next %}
							 <a href="?page={{ page_of_entries.next_page_number}}" aria-label="Next">
								<span aria-hidden="true">&laquo;</span>
							</a>
						{% else %}
							<span aria-hidden="true">&laquo;</span>
						{% endif %}	 
					</li>
				  </ul>
				<p>
					一共有{{ page_of_entries.paginator.count}}篇博客,
					当前第{{ page_of_entries.number }}页，
					共{{ page_of_entries.paginator.num_pages }}页
				</p>
			</div>
	</div>
		
		<div class="hidden-xs col-sm-4 col-md-4 col-lg-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Topic</h3>
					<button style="display:inline-block"><a href="{% url 'learning_logs:new_topic' %}" style="color:#000">
					Add new topic</a></button>
				</div>
				<div class="panel-body">
				<ul style="list-style-type:none;">
					{% for topic in topics %}
					<li>
						<h3>
							<a href="{% url 'learning_logs:topic' topic.id %}"  style="color:#000">{{ topic.text }}</a>({{topic.entry_count}})
						</h3>
					</li>
					{% empty %}
					<li>No topics have been added yet.</li>
					{% endfor %}
				</ul>
				<h3>
				</h3>
				</div>
			</div>
		
		<div class="panel panel-default">
			<div class="panel-heading">	日期归档</div>
			<div class="panel-body">
				<ul style="list-style-type:none">
					{% for entry_date,entry_count in entry_dates.items %}
						<li>
							<a href="{% url 'learning_logs:entry_date' entry_date.year entry_date.month %}">
							{{entry_date|date:'Y年m月'}}（{{entry_count}}）</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>
		</div>
	</div>
</div>
 <style text="css/text">
	div.row a{
		color:#000;
	}
	div.paginator{
		text-align:center;
	}
</style></body>
{% endblock %}