learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from . import views

urlpatterns = [
	path('admin/',admin.site.urls),
	path('', include('learning_logs.urls', namespace='learning_logs')),
	path('ckeditor',include('ckeditor_uploader.urls')),
	path('comment/',include('comment.urls')),
	path('user/',include('user.urls')),

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

learning_logs/urls.py
from django.urls import path
from . import views

app_name='learning_logs'
urlpatterns = [
	path('',views.index, name='index'),
	path('topics/', views.topics, name='topics'),
	path("topics/(?<topic_id>\d+)/",views.topic,name='topic'),
	path('new_topic/',views.new_topic,name='new_topic'),
	path('show_entry/(?<entry_id>\d+)/',views.show_entry,name='show_entry'),
	path('new_entry/(?<topic_id>\d+)/',views.new_entry,name='new_entry'),
	path('edit_entry/(?<entry_id>\d+)/',views.edit_entry,name='edit_entry'),
	# ~ path('del_entry/(?<entry_id>\d+)/',views.del_entry,name='del_entry'),
	path('entry_date/<int:year>/<int:month>',views.entry_date,name='entry_date'),
]

user/urls.py
from django.urls import path
from . import views
urlpatterns = [
	path('login/', views.login, name='login'),
	path('register/', views.register, name='register'),
	path('logout/', views.logout, name='logout'),
	path('user_info/', views.user_info, name='user_info'),
	path('change_nickname/', views.change_nickname, name='change_nickname'),
	path('bind_email/', views.bind_email, name='bind_email'),
	path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
	path('change_password/', views.change_password, name='change_password'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Learning Log</title>
	<link rel="stylesheet" href="{% static 'base.css' %}">
	<link rel="stylesheet" href="{% static 'bootstrap-3.3.7/css/bootstrap.min.css' %}">
	<script type="text/javascript" src="{% static 'jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>
<!--
    {% block header_extends %}{% endblock %}
-->
</head>
<body>
	<nav class="navbar navbar-default navbar-static-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
			    data-toggle="collapse" data-target="#navbar-collapse"
			    aria-expanded="false" aria-controls="navbar">
			    <span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
			Learning Log</a>
		</div>
		<div id="navbar-collapse" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="{% block nav_learninglog_active %}{% endblock %}">
					<a href="{% url 'learning_logs:index' %}">首页</a></li>
				<li class="{% block nav_topic_active %}{% endblock %}">
					<a href="{% url 'learning_logs:topics' %}">博客</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if user.is_authenticated %}
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">
						 {% if user.has_nickname %}
							{{user.username}}&nbsp;({{user.get_nickname}})
						 {% else %}
							{{user.username}}
						  {% endif %}
						  <span class="caret"></span>
					  </a>
					  <ul class="dropdown-menu">
						<li><a href="{% url 'user_info' %}">个人信息</a></li>
						{% if user.is_staff or user.is_superuser %}
							<li><a href="{% url 'admin:index' %}">后台管理</a></li>
						{% endif %}
						<li><a href="{% url 'change_password' %}" >修改密码</a></li>
						<li><a href="{% url 'logout' %}?from={{request.get_full_path }}">退出</a></li>
					  </ul>
					</li>
				{% else %}
					<li><a href="{% url 'login' %}?from={{request.get_full_path}}">登录</a></li>
					<li><a href="{% url 'register' %}?from={{request.get_full_path}}">注册</a></li>
				{% endif %}
			</ul>
		</div>
		</div>
	</nav>
	<div class="container">
	<div class="page-header">
		{% block header %}{% endblock header %}
	</div>
	<div>
		{% block content %}{% endblock content %}
		{% block script_extends %}{% endblock %}
	</div>
	</div> 
<style>
	ul.navbar-right{
		margin-right:0;
	}
</style>
</body>
</html>

templates/error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	我的网站|错误
{% endblock %}

{% block nav_home_active %}active{% endblock %}

{% block content %}
	{{ message }},<a href="{{ redirect_to }}">返回</a>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block title %}{{page_title}}{% endblock %}
{% block nav_home_active %}active{% endblock %}
{% block content %}
<div class="containter">
  <div class="row">
	<div class="col-xs-4 col-xs-offset-4">
	  <div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">{{form_title}}</h3>
		</div>
			<div class="panel-body">
				<form action="" method="POST">
					{% csrf_token %}
					{% for field in form %}
						<label for="{{field.id_for_label}}">{{field.label}}</label>
						{{ field}}
						<p class="text-danger"> {{field.errors.as_text}}</p>
					{% endfor %}
					<span id="tip" class="pull-left text-danger">{{form.non_field_errors}}</span>
					<div class="clearfix"></div>
					<div class="pull-left">
						{% block other-buttons %}{% endblock %}
					</div>
					<div class="pull-right">
						<input type="submit" value="{{submit_title}}" class="btn btn-primary">
						<button class="btn btn-default" onclick="window.location.href='{{return_back_url}}'">返回</button>
					</div>
				</form>
			</div>
		</div>
	  </div>
  </div>
</div>
{% endblock %}

 

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block header %}
  <div class='jumbotron'>
   <h1 style="font-family: 'Lobster' ;">Track your learning.</h1>
  </div>
{% endblock header %}
{% block nav_learninglog_active %}active{% endblock %}
{% block content %}
  <h2>
	  欢迎来到我的网站

  </h2>
  <h2>
    Whenever you learn something new about a topic, make an entry
	summarizing what you've learned.
   </h2>
{% endblock content %}